// Code generated by fsm-gen. DO NOT EDIT.
// source: door.fsm

package types

import "test/fsm"

var (
    FSMNameDoor = fsm.FSMName("Door")
    FSMNameSmartDoor = fsm.FSMName("SmartDoor")
)

var (
    StateOpen = fsm.FSMState("StateOpen")
    StateClose = fsm.FSMState("StateClose")
)

var (
    EventLock = fsm.FSMEvent("EventLock")
    EventUnlock = fsm.FSMEvent("EventUnlock")
)
