// Code generated by fsm-gen. DO NOT EDIT.
// source: door.fsm

package door

import (
	"test/fsm"
	"test/door/handlers"
	"test/door/types"
)


func NewFSMDoor() *fsm.FSM[types.Payload] {
	f := fsm.NewFSM[types.Payload](types.FSMNameDoor, types.StateClose)

	f.SetTransitions(
		fsm.NewTransitionItem(types.EventUnlock, types.StateClose, types.StateOpen, handlers.GetHandler_EventUnlock_StateClose()),
		fsm.NewTransitionItem(types.EventLock, types.StateOpen, types.StateClose, handlers.GetHandler_EventLock_StateOpen()),
	)

	return f
}

func NewFSMSmartDoor() *fsm.FSM[types.Payload] {
	f := fsm.NewFSM[types.Payload](types.FSMNameSmartDoor, types.StateClose)

	f.SetTransitions(
		fsm.NewTransitionItem(types.EventUnlock, types.StateClose, types.StateOpen, handlers.GetHandler_EventUnlock_StateClose()),
		fsm.NewTransitionItem(types.EventLock, types.StateOpen, types.StateClose, handlers.GetHandler_EventLock_StateOpen()),
		fsm.NewTransitionItem(types.EventUnlock, types.StateOpen, types.StateOpen, handlers.GetHandler_EventUnlock_StateOpen()),
	)

	return f
}
